### ISSUE TITLE
Support `getindex` of `TupleProductDomain` and maybe add a `NamedTupleProductDomain`?

### ISSUE THREAD

**Issue by findmyway** [JuliaApproximation/DomainSets.jl#119]
Sometimes, I'd like to access the sub-domains of a composite domain. It would be more intuitive to access them through the `getindex` method.

**Comment by daanhb** [comment]
I agree it makes sense for composite domains, but not for all domains. For example, in many parts of the code a vector `[1,2,3]` is just fine as a domain, and `getindex` means something entirely different. There is no generic way to define what `getindex` means for a domain except that, since a domain is a set, the first assumption is that `getindex` should return some element of that set. The behaviour for composite objects is that `components` returns its domain, and you can use `getindex` on that. Or, you can do `component(d, i)`, just like `getindex(d, i)`, only without the `[]` notation.

**Comment by findmyway** [comment]
I see. `component` should be enough for my use case. Thanks for your explanation!
