### ISSUE TITLE
Center for HyperRectangle?

### ISSUE THREAD

**Issue by philip-stuckey** [JuliaApproximation/DomainSets.jl#137]
Would it make sense to define the center of a hyper-rectangle as `center(rectangle::HyperRectangle)=center.(components(rectangle))`? Either way, I would find `center(::Rectangle)` useful.

**Comment by daanhb** [comment]
Thanks for the suggestion. I think it may make sense to define it for any product domain. Care to have a go at it?

**Comment by daanhb** [comment]
Hmm, I'm afraid the `ProductDomain` code is a bit overly complicated at the moment. It should be like the one-liner you write, but for a `ProductDomain` and perhaps with `factors` instead of `components` for clarity. If it isn't, then don't spend too much time and just go for the `HyperRectangle` like above.

**Comment by philip-stuckey** [comment]
I just added a function to `src/generic/productdomain.jl`, what I'm not sure about is where to put tests.
