### ISSUE TITLE
Support constructors along with `convert`

### ISSUE THREAD

**Issue by jishnub** [JuliaApproximation/DomainSets.jl#147]
Currently, using DomainSets v0.7.2, the following works:
```julia
julia> p = Point(2)
Point(2)

julia> convert(Int, p)
2
```
but the constructor doesn't:
```julia
julia> Int(p)
ERROR: MethodError: no method matching Int64(::Point{Int64})
```
It would be good if these were equivalent, with the convert method calling the constructor.

**Comment by daanhb** [comment]
Hmm, I'm not sure whether this is possible or desired. The conversion works because of these lines:
```julia
convert(::Type{Number}, d::Point{<:Number}) = d.x
convert(::Type{N}, d::Point{<:Number}) where N<:Number =
    convert(N, convert(Number, d.x))
Number(d::Point) = convert(Number, d)
```
This means that conversion to number types work for all number types.

However, `Int` is just one specific number type. Adding `Int(p::Point{Int})` is a bit random, because why not add `Float64(p::Point{Float64})` and all other possibilities? If there is no way to add all constructors, I think I'd rather add none.

**Comment by jishnub** [comment]
There is actually a way to add all possibilities by dispatching on the type of the constructor:
```julia
(::Type{T})(p::Point) where {T<:Number} = T(p.x)
```
e.g.:
```julia
julia> p = Point(3)
Point(3)

julia> (::Type{T})(p::Point) where {T<:Number} = T(p.x)

julia> Int(p)
3

julia> Float64(p)
3.0
```

**Comment by daanhb** [comment]
Did not know that - alright, that makes the constructor more appropriate than convert. There are probably more instances of this in the package.
