### ISSUE TITLE
5 in ℝ returns false

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/DomainSets.jl#51]
```
julia> 5 in ℝ
false
```
Also, its weird that `ℝ` is a type, not an instance

**Comment by daanhb** [comment]
That is because these are spaces, not domains. I guess they should not be exported like that, and perhaps spaces can be removed altogether. Spaces were meant to give a mechanism to define embeddings and isomorphisms in a type-stable way.

If we define these as domains, then R, Q and friends are all `FullSpace`s. R could be defined as`FullSpace{Float64}()`?

**Comment by dlfivefifty** [comment]
Whatever the implementation, the behaviour 
```Julia
julia> 5 in ℝ
false
```
is clearly wrong... ` FullSpace{Float64}() ` sounds fine as long as the above is fixed

**Comment by daanhb** [comment]
Okay, I made all of them into a `FullSpace`.
Somehow, I think by locally activating the package for development, the version string is now 0.1.0 rather than 0.1 as before. We may want to bump it anyhow with the latest changes.
